# ABOUTME: Type stubs for C++ DataLoader PyBind11 bindings.
# ABOUTME: Provides type annotations for _lczero_training compiled module.

from typing import List, Tuple

import numpy as np

class TensorBase:
    def shape(self) -> List[int]: ...
    def strides(self) -> List[int]: ...
    def element_size(self) -> int: ...
    def py_format(self) -> str: ...

class DataLoader:
    def __init__(self, config: bytes) -> None: ...
    def get_next(self) -> Tuple[np.ndarray, ...]: ...
    def close(self, graceful_drain: bool = False) -> None: ...
    def get_bucket_metrics(
        self, time_period: int, include_pending: bool
    ) -> Tuple[bytes, float]: ...
    def get_aggregate_ending_now(
        self, duration_seconds: float, include_pending: bool
    ) -> Tuple[bytes, float]: ...
