# ABOUTME: Type stubs for C++ DataLoader PyBind11 bindings.
# ABOUTME: Provides type annotations for _lczero_training compiled module.

from typing import List, Tuple

import numpy as np

from proto.data_loader_config_pb2 import DataLoaderConfig
from proto.stage_control_pb2 import StageControlRequest, StageControlResponse

class TensorBase:
    def shape(self) -> List[int]: ...
    def strides(self) -> List[int]: ...
    def element_size(self) -> int: ...
    def py_format(self) -> str: ...

class DataLoader:
    def __init__(self, config: DataLoaderConfig | bytes) -> None: ...
    def add_stages(self, config: DataLoaderConfig | bytes) -> None: ...
    def send_control_message(
        self, request: StageControlRequest | bytes
    ) -> List[Tuple[str, StageControlResponse]]: ...
    def start(self) -> None: ...
    def get_next(self, alias: str = "") -> Tuple[np.ndarray, ...]: ...
    def stop(self) -> None: ...
    def get_bucket_metrics(
        self, time_period: int, include_pending: bool
    ) -> Tuple[bytes, float]: ...
    def get_aggregate_ending_now(
        self, duration_seconds: float, include_pending: bool
    ) -> Tuple[bytes, float]: ...
