# ABOUTME: Type stubs for C++ DataLoader PyBind11 bindings.
# ABOUTME: Provides type annotations for _lczero_training compiled module.

from typing import Tuple, List
import numpy as np

class TensorBase:
    def shape(self) -> List[int]: ...
    def strides(self) -> List[int]: ...
    def element_size(self) -> int: ...
    def py_format(self) -> str: ...

class DataLoader:
    def __init__(self, config: bytes) -> None: ...
    def get_next(self) -> Tuple[np.ndarray, ...]: ...
    def get_1_second_stats(self) -> bytes: ...
    def get_total_stats(self) -> bytes: ...
